version: '3'

services:

  server:
    container_name: mcpe-server
    # Delete string "build: ./php" if you want use complate image from dockerhub
    build: ./php
    image: xackigiff/mcpe-php:latest
    volumes:
      - ./server:/home/mcpe/server
    command: /bin/bash -c 'cd /home/mcpe/server/ && ./start.sh -l'
    ports:
      - 19132:19132/tcp
      - 19132:19132/udp
      - 19133:19133/tcp
      - 19133:19133/udp
