name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test build the Docker image for PHP
      run: docker build ./php/ --file ./php/Dockerfile --tag xackigiff/mcpe-php-8:$(date +%s)
    - name: Test build the Docker image for PHP
      run: docker build ./build/composer --file ./php/Dockerfile --tag xackigiff/mcpe-php-8:$(date +%s)
    - name: Test start the Docker image
      run: docker compose up
