name: Main MCPE-PHP workflow by XackiGiFF

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  # Install all needs libs in image
  app_install_and_push_to_docker_hub:
    name: Make image mcpe-php-image:latest and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push base image to DockerHub
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./php/install/
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/mcpe-php-image:latest

  # Build PM4
  pm4_build_and_push_to_docker_hub:
    name: Make PM4 and push to DockerHub
    needs: app_install_and_push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PM4 to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./php/build/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mcpe-php:pm4
          secrets: |
            HOME_DIR=/home/mcpe
            PM_VERSION=4
            PMMP_API=4.20.0
            PHP_VERSION=php-8.1-latest
            GIT_HASH=a34e48e7da75


  # Build PM5
  pm5_build_and_push_to_docker_hub:
    name: Make PM5 and push to DockerHub
    needs: app_install_and_push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PM5 to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./php/build/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mcpe-php:pm4
          secrets: |
            HOME_DIR=/home/mcpe
            PM_VERSION=5
            PMMP_API=5
            PHP_VERSION=php-8.2-latest
            GIT_HASH=d5c2d1669f89

  # Merge PM4 & PM5
  mcpe_merge_and_push_to_docker_hub:
    name: Merge PM4&PM5 and push to DockerHub
    needs:
      - pm4_build_and_push_to_docker_hub
      - pm5_build_and_push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push merged pm4&pm5 to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./php/install/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mcpe-php:latest

  
  send_message_complete_image:
    runs-on: ubuntu-latest
    needs: app_install_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Образ системы успешно подготовлен: xackigiff/mcpe-php-image:latest"

  send_message_complete_pm4:
    runs-on: ubuntu-latest
    needs: pm4_build_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "PM4 успешно собран: xackigiff/mcpe-php:pm4"

  send_message_complete_pm5:
    runs-on: ubuntu-latest
    needs: pm5_build_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "PM5 успешно собран: xackigiff/mcpe-php:pm5"

  send_message_complete_merge:
    runs-on: ubuntu-latest
    needs: mcpe_merge_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Merge PM4 и PM5 успешно: xackigiff/mcpe-php:latest"

  send_message_complete_deploy:
    runs-on: ubuntu-latest
    needs: mcpe_merge_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой ${{ github.event.repository.name }} успешно выполнен!
